import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "./component";
import { Suspense } from "react";
import { CartProvider } from "./context/CartContext";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Suspense fallback={<h3>Loading...</h3>}>
        <CartProvider>
          {/* Navbar Stays on Top */}
          <Navbar />
          {/* Content Below Navbar */}
          <main className="container mx-auto px-6 py-20">
            {children}
          </main>
          </CartProvider>
        </Suspense>
      </body>
    </html>
  );
}
